### ISSUE TITLE
Question: Python 2 or 3?

### ISSUE THREAD

**Issue by wschoenell** [LCOGT/banzai#90]
Maybe a silly question, but are you running this code in Python 2 or 3? I did not found this info in the docs...

Thanks!

**Comment by cmccully** [comment]
Banzai is designed to work with either. Are you having any issues on a particular version of Python?

**Comment by wschoenell** [comment]
Thanks! 

I do have some issues to run it in Python 2.7, like some methods that do not exist (like `tempfile.TemporaryDirectory()`, which was introduced on Python 3.2), but nothing too critical... I will issue a PR as soon I am able to run the pipeline for one night of the telescope that I have (it is a robotic 0.4m in Brazil).

**Comment by cmccully** [comment]
Very cool! Let me know if you find any other issues. Out of curiosity, is python 3 an option?

**Comment by wschoenell** [comment]
yes... it is... I just used 2.7 as it is the one I had installed... Will try in Python3. Thanks!

**Comment by wschoenell** [comment]
Closing this issue... I send you an e-mail if I have more comments... Thanks for your time.
